### ISSUE TITLE
Remove default Greater Orlando info

### ISSUE THREAD

**Issue by EzraKuhr** [radius314/bread#35]
When a service body (or someone else using bread) doesnt bother to fill in the right information for the body, it defaults to Greater Orlando.

**Comment by EzraKuhr** [comment]
Possibly force the user in the initial set up to enter in helpline info (or specify that there is none) and other front page info instead of assuming they will change it in the editor.

**Comment by pjaudiomv** [comment]
this is a pretty easy change, however I feel like someone should be the default so that an actual root server can be added and happy. there are admin warning messages that pop up when not set. If people feel differently we can just make it a dummy non actual root server setting. It would be super easy to change the phone line numbers and just change Orlando to something like Your Service body or whatever.

**Comment by EzraKuhr** [comment]
Itd be great if say we had a national helpline that we could default to.... just a thought.

(Doesnt really help anyone outside the US though)

**Comment by radius314** [comment]
released in bread 1.7.0
